version: 2.1

jobs:
  lint:
    docker:
      - image: randomgraphics/rapid-vulkan:latest
    steps:
      - run:
          name: prep git
          command: |
            git config --global --add safe.directory /tmp/_circleci_local_build_repo
            git config --global --add safe.directory /root/project
      - checkout
      - run: dev/bin/cit.py -l

  build-linux-gcc-with-cit:
    docker:
      - image: randomgraphics/rapid-vulkan:latest
    steps:
      - run:
          name: prep git
          command: |
            git config --global --add safe.directory /tmp/_circleci_local_build_repo
            git config --global --add safe.directory /root/project
      - checkout
      - run:
          name: build
          command: |
            source dev/env/env.rc
            build.py d
            build.py p
            build.py r
            build/posix.gcc.d/dev/test/rapid-vulkan-test
            build/posix.gcc.p/dev/test/rapid-vulkan-test
            build/posix.gcc.r/dev/test/rapid-vulkan-test

  build-linux-clang:
    docker:
      - image: randomgraphics/rapid-vulkan:latest
    steps:
      - run:
          name: prep git
          command: |
            git config --global --add safe.directory /tmp/_circleci_local_build_repo
            git config --global --add safe.directory /root/project
      - checkout
      - run:
          name: build
          command: |
            source dev/env/env.rc
            build.py --clang -n d
            build.py --clang -n p
            build.py --clang -n r

  build-android:
    docker:
      - image: randomgraphics/rapid-vulkan:android-latest
    steps:
      - run:
          name: prep git
          command: |
            git config --global --add safe.directory /tmp/_circleci_local_build_repo
            git config --global --add safe.directory /root/project
      - checkout
      - run:
          name: build
          command: |
            source dev/env/env.rc
            build.py -a d
            build.py -a p
            build.py -a r

workflows:
  build-and-test:
    jobs:
      - lint
      - build-linux-gcc-with-cit:
          requires:
            - lint
      - build-linux-clang:
          requires:
            - lint
      - build-android:
          requires:
            - lint
