version: 2.1

jobs:
  lint:
    docker:
      - image: randomgraphics/rapid-vulkan:latest
    steps:
      - run:
          name: prep git
          command: |
            git config --global --add safe.directory /tmp/_circleci_local_build_repo
            git config --global --add safe.directory /root/project
      - checkout
      - run: dev/bin/cit.py -l

  build-linux:
    docker:
      - image: randomgraphics/rapid-vulkan:latest
    steps:
      - run:
          name: prep git
          command: |
            git config --global --add safe.directory /tmp/_circleci_local_build_repo
            git config --global --add safe.directory /root/project
      - checkout
      - run:
          name: build
          command: |
            source dev/env/env.rc
            build.py d
            build.py p
            build.py r

workflows:
  build-and-test:
    jobs:
      - lint
      - build-linux:
          requires:
            - lint
